export const productsList = [
  {
    id: 0,
    name: "Chaise Molle",
    price: 18,
    image: require("../assets/chair_1.png"),
    type: "chair",
    positiony: "30px",
  },
  {
    id: 1,
    name: "Chaise Molle",
    price: 18,
    image: require("../assets/chair_2.png"),
    type: "chair",
  },
  {
    id: 2,
    name: "Chaise Molle",
    price: 18,
    image: require("../assets/chair_3.png"),
    type: "chair",
  },
  {
    id: 3,
    name: "Chaise Molle",
    price: 18,
    image: require("../assets/lamp.png"),
    type: "lamp",
  },
  {
    id: 4,
    name: "Chaise Molle",
    price: 48,
    image: require("../assets/table.png"),
    type: "table",
  },
  {
    id: 5,
    name: "Chaise Molle",
    price: 78,
    image: require("../assets/couch.png"),
    type: "sofa",
  },
];